name: "Go Reusable Workflow"

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: "1.20.x"
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  go-build-test-lint:
    name: "Runs Go CI steps"
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/martelskiy/*
      TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}
          cache: true
      
      - name: Configure git for private modules
        run: git config --global url.https://martelskiy:$TOKEN@github.com.insteadOf https://github.com

      - name: Build
        run: make build

      - name: Test
        run: make test
      
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest