name: "Go Reusable Workflow"

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: "1.21.x"
      upload-build-artifact-path:
        description: "Path to upload Go binary artifact"
        required: false
        type: string
      artifact-name:
        description: "Go binary artifact name. Required if upload-build-artifact-path input is set"
        required: false
        type: string
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  go-lint:
    name: "Runs Go Linter steps"
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/martelskiy/*
      TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: false

      - name: Configure git for private modules
        run: git config --global url.https://martelskiy:$TOKEN@github.com.insteadOf https://github.com

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

  go-build-test:
    name: "Runs Go CI steps"
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/martelskiy/*
      TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - name: Configure git for private modules
        run: git config --global url.https://martelskiy:$TOKEN@github.com.insteadOf https://github.com

      - name: Build
        run: make build

      - uses: actions/upload-artifact@v4
        if: inputs.upload-build-artifact-path != ''
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.upload-build-artifact-path }}

      - name: Test
        run: make test
